// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/gstanleysilva/go-sqlc-example/infra/repositories"
	"github.com/gstanleysilva/go-sqlc-example/internal/domain"
	"github.com/gstanleysilva/go-sqlc-example/internal/services/category"
	"github.com/gstanleysilva/go-sqlc-example/internal/services/coursecategory"
)

// Injectors from wire.go:

func NewGetCategoryService(db *sql.DB) *category.GetCategoryService {
	categoryRepository := repositories.NewCategoryRepository(db)
	getCategoryService := category.NewGetCategoryService(categoryRepository)
	return getCategoryService
}

func NewCreateCategoryService(db *sql.DB) *category.CreateCategoryService {
	categoryRepository := repositories.NewCategoryRepository(db)
	createCategoryService := category.NewCreateCategoryService(categoryRepository)
	return createCategoryService
}

func NewCreateCourseAndCategoryUowService(db *sql.DB) *coursecategory.CreateCourseAndCategoryUowService {
	courseAndCategoryUow := coursecategory.NewCourseAndCategoryUow(db)
	createCourseAndCategoryUowService := coursecategory.NewCreateCourseAndCategoryUowService(courseAndCategoryUow)
	return createCourseAndCategoryUowService
}

func NewGetCoursesWithCategoryService(db *sql.DB) *coursecategory.GetCoursesWithCategoryService {
	courseCategoryRepository := repositories.NewCourseCategoryRepository(db)
	getCoursesWithCategoryService := coursecategory.NewGetCoursesWithCategoryService(courseCategoryRepository)
	return getCoursesWithCategoryService
}

func NewCreateCourseAndCategoryService(db *sql.DB) *coursecategory.CreateCourseWithCategoryService {
	courseCategoryRepository := repositories.NewCourseCategoryRepository(db)
	createCourseWithCategoryService := coursecategory.NewCreateCourseWithCategoryService(courseCategoryRepository)
	return createCourseWithCategoryService
}

// wire.go:

var setRepositoryDependency = wire.NewSet(repositories.NewCourseCategoryRepository, wire.Bind(new(domain.CourseCategoryRepository), new(*repositories.CourseCategoryRepository)), repositories.NewCategoryRepository, wire.Bind(new(domain.CategoryRepository), new(*repositories.CategoryRepository)))
